### ISSUE TITLE
Malformed lineage designations

### ISSUE THREAD

**Issue by ciscorucinski** [corneliusroemer/pango-designation-dates#2]
[Line 2605 - 2607](https://github.com/corneliusroemer/pango-designation-dates/blob/main/data/lineage_designation_date.csv#L2605) have the wrong designation code assigned to them. 

lineage | designation_date
-- | --
XBC.XAY.2.1 | 2023-02-11
XBC.XAY.2.2 | 2023-02-11
XBC.XAY.1 | 2023-02-11

It is possible that these 3 can be deleted. There are 2 apparent duplicates below these malformed entries, and the last malformed one doesn't appear to be correctable.

**Additional context**  
https://github.com/cov-lineages/pango-designation/commit/1dcf0fe12f35f73feba7c529d365c9f721928dd8

![Screenshot from 2023-02-11 16-18-50](https://user-images.githubusercontent.com/8707125/218245983-1a80edb5-6530-44b9-a6ae-768adeace2a6.png)

**Comment by corneliusroemer** [comment]
This has been fixed in a later commit - I mistyped along the way ;)

**Comment by ciscorucinski** [comment]
The malformed lineages are still present in `main`. Shouldn't they be removed?  It looks like both the malformed and corrected lineages were both pushed at the same time https://github.com/corneliusroemer/pango-designation-dates/commit/41f39797e588c38a722ed2f7d20b62bef603f3d6

**Comment by corneliusroemer** [comment]
Aaah, I get it! It's fixed in the main designations but not in the designation dates. Sorry!
